### ISSUE TITLE
Pi column not estimated

### ISSUE THREAD

**Issue by kvittingseerup** [SimoneTiberi/IsoBayes#5]
Hi Again

I've just run into a strange problem in that IsoBayes runs perfectly but the `Pi` column in the `isoform_results` output is purely NAs (and it is the same in `normalized_isoform_results`).

The problem can be recreated with this [quant file](https://www.dropbox.com/scl/fi/xgdqtvth8s9se5yhh1ifu/PXD004273__intensity_ko1_lys_1.tsv?rlkey=7w8qjf7rcahaguw8ve52mhl5q&dl=0) , this [iso_mapping file](https://www.dropbox.com/scl/fi/uf2gfew09di8aj82wqy1p/16_0_map_iso_gene.csv?rlkey=h5jzoqcmvty4v3wultdziegv5&dl=0) and this code

```
 data_loaded <- IsoBayes::load_data(
    path_to_peptides_psm = "test/PXD004273__intensity_ko1_lys_1.tsv",
    input_type = "other",
    PEP = FALSE
  )
  
  isoRes <- IsoBayes::inference(
    loaded_data = data_loaded,
    map_iso_gene = 'test/16_0_map_iso_gene.csv'
  )
  
  table(is.na(isoRes$isoform_results$Pi))
   TRUE 
  18408 
```

P.s. interestingly, in the `normalized_isoform_results`, the `Pi` confidence interval is estimated.

**Comment by jbollon** [comment]
Hi @kvittingseerup ,
you are running into the numerical issue we faced with the intensities. When the scale of the intensities is too large, all the isoforms are considered as present (Probability of being present in the sample is always 1). This happens because even the least likely isoform will receive a small fraction of the peptide intensity. For instance, let's say we have one peptide that maps to two isoforms (A and B). Suppose we know the true relative abundance for A (extremely high) and B (extremely low). In such scenario, during the estimation of the probability of being present in the sample, IsoBayes allocate (almost always) all the peptide abundance (intensity) to A, returning a probability of being present close to 1 for A and close to 0 for B. BUT, if the peptide intensity is extremely high, even if the true relative abundance for B is extremely low, a small fraction of the abundance will be always inputted to B. Therefore, all the isoforms will have a probability of being present equal to 1.

To overcome this issue, we normalize the intensities (see #2).

Now, going back to your analysis, if you set the abundance_type as "intensities", IsoBayes will normalize your intensities as explained #2 . I did it with your data and code and it works!

In addition, I'm going to modify the vignettes where we state "Note that, when using user-provided data, arguments abundance_type and path_to_peptides_intensities are not considered, because users are free to set column Y to PSM counts or intensities.". I think abundance_type must be set to "intensities" if the user inputs intensities.

Anyway, thanks for trying IsoBayes. We were aware about this numerical issue and we are going to make some adjustments to avoid its recurrence. For now, the solution is to set abundance_type = "intensities" or trying your own normalization/transformation.

Cheers,
Jordy

**Comment by kvittingseerup** [comment]
Thanks for the clarification - that makes a lot of sense 🙂. And thanks for pointing out the `abundance_type = "intensities"` - I misinterpreted that as only being available when `"input_type = metamorpheus"` 😅

Regarding the input normalization, what distribution do you assume/require intensities (imported via `abundance_type = "intensities"`) follow?

**Comment by jbollon** [comment]
We do not assume a distribution of data. So far, the model has worked without any data distribution requirement.  Please let us know if you have problems with any dataset you have.

Cheers!
Jb

**Comment by kvittingseerup** [comment]
Thanks again for your quick reply!
